# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: ubuntu_16_04
    displayName: 'Build - Ubuntu 16.04'
    continueOnError: false
    pool:
      vmImage: 'Ubuntu 16.04'
    workspace:
      clean: all
    steps:
      - task: DockerCompose@0
        displayName: Build services
        inputs:
          action: Build
          containerregistrytype: Container Registry
          dockerComposeFile: docker-compose.yaml
      - task: DockerCompose@0
        displayName: Run Tests
        inputs:
          action: Run
          containerregistrytype: Container Registry
          dockerComposeFile: docker-compose.yaml
          serviceName: test
          detached: true
